/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as OnboardingRouteImport } from './routes/onboarding'
import { Route as AuthRouteImport } from './routes/auth'
import { Route as AuthenticatedRouteRouteImport } from './routes/_authenticated/route'
import { Route as IndexRouteImport } from './routes/index'
import { Route as CCodeRouteImport } from './routes/c.$code'
import { Route as AddCodeRouteImport } from './routes/add.$code'
import { Route as AuthenticatedWakeRouteImport } from './routes/_authenticated/wake'
import { Route as AuthenticatedSettingsRouteImport } from './routes/_authenticated/settings'
import { Route as AuthenticatedInboxRouteImport } from './routes/_authenticated/inbox'
import { Route as AuthenticatedHomeRouteImport } from './routes/_authenticated/home'
import { Route as AuthenticatedCircleRouteImport } from './routes/_authenticated/circle'
import { Route as AuthenticatedChannelsRouteImport } from './routes/_authenticated/channels'
import { Route as AuthenticatedChannelsIndexRouteImport } from './routes/_authenticated/channels.index'
import { Route as AuthenticatedChannelsNewRouteImport } from './routes/_authenticated/channels.new'
import { Route as AuthenticatedChannelsMineRouteImport } from './routes/_authenticated/channels.mine'
import { Route as AuthenticatedChannelsSlugRouteImport } from './routes/_authenticated/channels.$slug'
import { Route as ApiPublicHooksWakeTickRouteImport } from './routes/api/public/hooks/wake-tick'

const OnboardingRoute = OnboardingRouteImport.update({
  id: '/onboarding',
  path: '/onboarding',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthRoute = AuthRouteImport.update({
  id: '/auth',
  path: '/auth',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedRouteRoute = AuthenticatedRouteRouteImport.update({
  id: '/_authenticated',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const CCodeRoute = CCodeRouteImport.update({
  id: '/c/$code',
  path: '/c/$code',
  getParentRoute: () => rootRouteImport,
} as any)
const AddCodeRoute = AddCodeRouteImport.update({
  id: '/add/$code',
  path: '/add/$code',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedWakeRoute = AuthenticatedWakeRouteImport.update({
  id: '/wake',
  path: '/wake',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedSettingsRoute = AuthenticatedSettingsRouteImport.update({
  id: '/settings',
  path: '/settings',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedInboxRoute = AuthenticatedInboxRouteImport.update({
  id: '/inbox',
  path: '/inbox',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedHomeRoute = AuthenticatedHomeRouteImport.update({
  id: '/home',
  path: '/home',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedCircleRoute = AuthenticatedCircleRouteImport.update({
  id: '/circle',
  path: '/circle',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedChannelsRoute = AuthenticatedChannelsRouteImport.update({
  id: '/channels',
  path: '/channels',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedChannelsIndexRoute =
  AuthenticatedChannelsIndexRouteImport.update({
    id: '/',
    path: '/',
    getParentRoute: () => AuthenticatedChannelsRoute,
  } as any)
const AuthenticatedChannelsNewRoute =
  AuthenticatedChannelsNewRouteImport.update({
    id: '/new',
    path: '/new',
    getParentRoute: () => AuthenticatedChannelsRoute,
  } as any)
const AuthenticatedChannelsMineRoute =
  AuthenticatedChannelsMineRouteImport.update({
    id: '/mine',
    path: '/mine',
    getParentRoute: () => AuthenticatedChannelsRoute,
  } as any)
const AuthenticatedChannelsSlugRoute =
  AuthenticatedChannelsSlugRouteImport.update({
    id: '/$slug',
    path: '/$slug',
    getParentRoute: () => AuthenticatedChannelsRoute,
  } as any)
const ApiPublicHooksWakeTickRoute = ApiPublicHooksWakeTickRouteImport.update({
  id: '/api/public/hooks/wake-tick',
  path: '/api/public/hooks/wake-tick',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/auth': typeof AuthRoute
  '/onboarding': typeof OnboardingRoute
  '/channels': typeof AuthenticatedChannelsRouteWithChildren
  '/circle': typeof AuthenticatedCircleRoute
  '/home': typeof AuthenticatedHomeRoute
  '/inbox': typeof AuthenticatedInboxRoute
  '/settings': typeof AuthenticatedSettingsRoute
  '/wake': typeof AuthenticatedWakeRoute
  '/add/$code': typeof AddCodeRoute
  '/c/$code': typeof CCodeRoute
  '/channels/$slug': typeof AuthenticatedChannelsSlugRoute
  '/channels/mine': typeof AuthenticatedChannelsMineRoute
  '/channels/new': typeof AuthenticatedChannelsNewRoute
  '/channels/': typeof AuthenticatedChannelsIndexRoute
  '/api/public/hooks/wake-tick': typeof ApiPublicHooksWakeTickRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/auth': typeof AuthRoute
  '/onboarding': typeof OnboardingRoute
  '/circle': typeof AuthenticatedCircleRoute
  '/home': typeof AuthenticatedHomeRoute
  '/inbox': typeof AuthenticatedInboxRoute
  '/settings': typeof AuthenticatedSettingsRoute
  '/wake': typeof AuthenticatedWakeRoute
  '/add/$code': typeof AddCodeRoute
  '/c/$code': typeof CCodeRoute
  '/channels/$slug': typeof AuthenticatedChannelsSlugRoute
  '/channels/mine': typeof AuthenticatedChannelsMineRoute
  '/channels/new': typeof AuthenticatedChannelsNewRoute
  '/channels': typeof AuthenticatedChannelsIndexRoute
  '/api/public/hooks/wake-tick': typeof ApiPublicHooksWakeTickRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/_authenticated': typeof AuthenticatedRouteRouteWithChildren
  '/auth': typeof AuthRoute
  '/onboarding': typeof OnboardingRoute
  '/_authenticated/channels': typeof AuthenticatedChannelsRouteWithChildren
  '/_authenticated/circle': typeof AuthenticatedCircleRoute
  '/_authenticated/home': typeof AuthenticatedHomeRoute
  '/_authenticated/inbox': typeof AuthenticatedInboxRoute
  '/_authenticated/settings': typeof AuthenticatedSettingsRoute
  '/_authenticated/wake': typeof AuthenticatedWakeRoute
  '/add/$code': typeof AddCodeRoute
  '/c/$code': typeof CCodeRoute
  '/_authenticated/channels/$slug': typeof AuthenticatedChannelsSlugRoute
  '/_authenticated/channels/mine': typeof AuthenticatedChannelsMineRoute
  '/_authenticated/channels/new': typeof AuthenticatedChannelsNewRoute
  '/_authenticated/channels/': typeof AuthenticatedChannelsIndexRoute
  '/api/public/hooks/wake-tick': typeof ApiPublicHooksWakeTickRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/auth'
    | '/onboarding'
    | '/channels'
    | '/circle'
    | '/home'
    | '/inbox'
    | '/settings'
    | '/wake'
    | '/add/$code'
    | '/c/$code'
    | '/channels/$slug'
    | '/channels/mine'
    | '/channels/new'
    | '/channels/'
    | '/api/public/hooks/wake-tick'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/auth'
    | '/onboarding'
    | '/circle'
    | '/home'
    | '/inbox'
    | '/settings'
    | '/wake'
    | '/add/$code'
    | '/c/$code'
    | '/channels/$slug'
    | '/channels/mine'
    | '/channels/new'
    | '/channels'
    | '/api/public/hooks/wake-tick'
  id:
    | '__root__'
    | '/'
    | '/_authenticated'
    | '/auth'
    | '/onboarding'
    | '/_authenticated/channels'
    | '/_authenticated/circle'
    | '/_authenticated/home'
    | '/_authenticated/inbox'
    | '/_authenticated/settings'
    | '/_authenticated/wake'
    | '/add/$code'
    | '/c/$code'
    | '/_authenticated/channels/$slug'
    | '/_authenticated/channels/mine'
    | '/_authenticated/channels/new'
    | '/_authenticated/channels/'
    | '/api/public/hooks/wake-tick'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AuthenticatedRouteRoute: typeof AuthenticatedRouteRouteWithChildren
  AuthRoute: typeof AuthRoute
  OnboardingRoute: typeof OnboardingRoute
  AddCodeRoute: typeof AddCodeRoute
  CCodeRoute: typeof CCodeRoute
  ApiPublicHooksWakeTickRoute: typeof ApiPublicHooksWakeTickRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/onboarding': {
      id: '/onboarding'
      path: '/onboarding'
      fullPath: '/onboarding'
      preLoaderRoute: typeof OnboardingRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/auth': {
      id: '/auth'
      path: '/auth'
      fullPath: '/auth'
      preLoaderRoute: typeof AuthRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated': {
      id: '/_authenticated'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof AuthenticatedRouteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/c/$code': {
      id: '/c/$code'
      path: '/c/$code'
      fullPath: '/c/$code'
      preLoaderRoute: typeof CCodeRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/add/$code': {
      id: '/add/$code'
      path: '/add/$code'
      fullPath: '/add/$code'
      preLoaderRoute: typeof AddCodeRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated/wake': {
      id: '/_authenticated/wake'
      path: '/wake'
      fullPath: '/wake'
      preLoaderRoute: typeof AuthenticatedWakeRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/settings': {
      id: '/_authenticated/settings'
      path: '/settings'
      fullPath: '/settings'
      preLoaderRoute: typeof AuthenticatedSettingsRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/inbox': {
      id: '/_authenticated/inbox'
      path: '/inbox'
      fullPath: '/inbox'
      preLoaderRoute: typeof AuthenticatedInboxRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/home': {
      id: '/_authenticated/home'
      path: '/home'
      fullPath: '/home'
      preLoaderRoute: typeof AuthenticatedHomeRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/circle': {
      id: '/_authenticated/circle'
      path: '/circle'
      fullPath: '/circle'
      preLoaderRoute: typeof AuthenticatedCircleRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/channels': {
      id: '/_authenticated/channels'
      path: '/channels'
      fullPath: '/channels'
      preLoaderRoute: typeof AuthenticatedChannelsRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/channels/': {
      id: '/_authenticated/channels/'
      path: '/'
      fullPath: '/channels/'
      preLoaderRoute: typeof AuthenticatedChannelsIndexRouteImport
      parentRoute: typeof AuthenticatedChannelsRoute
    }
    '/_authenticated/channels/new': {
      id: '/_authenticated/channels/new'
      path: '/new'
      fullPath: '/channels/new'
      preLoaderRoute: typeof AuthenticatedChannelsNewRouteImport
      parentRoute: typeof AuthenticatedChannelsRoute
    }
    '/_authenticated/channels/mine': {
      id: '/_authenticated/channels/mine'
      path: '/mine'
      fullPath: '/channels/mine'
      preLoaderRoute: typeof AuthenticatedChannelsMineRouteImport
      parentRoute: typeof AuthenticatedChannelsRoute
    }
    '/_authenticated/channels/$slug': {
      id: '/_authenticated/channels/$slug'
      path: '/$slug'
      fullPath: '/channels/$slug'
      preLoaderRoute: typeof AuthenticatedChannelsSlugRouteImport
      parentRoute: typeof AuthenticatedChannelsRoute
    }
    '/api/public/hooks/wake-tick': {
      id: '/api/public/hooks/wake-tick'
      path: '/api/public/hooks/wake-tick'
      fullPath: '/api/public/hooks/wake-tick'
      preLoaderRoute: typeof ApiPublicHooksWakeTickRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

interface AuthenticatedChannelsRouteChildren {
  AuthenticatedChannelsSlugRoute: typeof AuthenticatedChannelsSlugRoute
  AuthenticatedChannelsMineRoute: typeof AuthenticatedChannelsMineRoute
  AuthenticatedChannelsNewRoute: typeof AuthenticatedChannelsNewRoute
  AuthenticatedChannelsIndexRoute: typeof AuthenticatedChannelsIndexRoute
}

const AuthenticatedChannelsRouteChildren: AuthenticatedChannelsRouteChildren = {
  AuthenticatedChannelsSlugRoute: AuthenticatedChannelsSlugRoute,
  AuthenticatedChannelsMineRoute: AuthenticatedChannelsMineRoute,
  AuthenticatedChannelsNewRoute: AuthenticatedChannelsNewRoute,
  AuthenticatedChannelsIndexRoute: AuthenticatedChannelsIndexRoute,
}

const AuthenticatedChannelsRouteWithChildren =
  AuthenticatedChannelsRoute._addFileChildren(
    AuthenticatedChannelsRouteChildren,
  )

interface AuthenticatedRouteRouteChildren {
  AuthenticatedChannelsRoute: typeof AuthenticatedChannelsRouteWithChildren
  AuthenticatedCircleRoute: typeof AuthenticatedCircleRoute
  AuthenticatedHomeRoute: typeof AuthenticatedHomeRoute
  AuthenticatedInboxRoute: typeof AuthenticatedInboxRoute
  AuthenticatedSettingsRoute: typeof AuthenticatedSettingsRoute
  AuthenticatedWakeRoute: typeof AuthenticatedWakeRoute
}

const AuthenticatedRouteRouteChildren: AuthenticatedRouteRouteChildren = {
  AuthenticatedChannelsRoute: AuthenticatedChannelsRouteWithChildren,
  AuthenticatedCircleRoute: AuthenticatedCircleRoute,
  AuthenticatedHomeRoute: AuthenticatedHomeRoute,
  AuthenticatedInboxRoute: AuthenticatedInboxRoute,
  AuthenticatedSettingsRoute: AuthenticatedSettingsRoute,
  AuthenticatedWakeRoute: AuthenticatedWakeRoute,
}

const AuthenticatedRouteRouteWithChildren =
  AuthenticatedRouteRoute._addFileChildren(AuthenticatedRouteRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AuthenticatedRouteRoute: AuthenticatedRouteRouteWithChildren,
  AuthRoute: AuthRoute,
  OnboardingRoute: OnboardingRoute,
  AddCodeRoute: AddCodeRoute,
  CCodeRoute: CCodeRoute,
  ApiPublicHooksWakeTickRoute: ApiPublicHooksWakeTickRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
